### ISSUE TITLE
sales tab in admin gives Internal server error

### ISSUE THREAD

**Issue by magdalenesuo** [fossasia/open-event-orga-server#2984] opened 2017-01-19 15:24 UTC
![screenshot from 2017-01-19 20-41-54](https://cloud.githubusercontent.com/assets/20799954/22112565/6d75ceee-de89-11e6-957b-2088f73eab8f.png)

**Comment by niranjan94** [comment] 2017-01-19 16:03
Duplicate of #2969

**Closed by niranjan94** 2017-01-19 16:03 UTC
