### ISSUE TITLE
Events not displayed in the home page of eventyay.com

### ISSUE THREAD

**Issue by niranjan94** [fossasia/open-event-orga-server#3743] opened 2017-06-07 14:39 UTC
**I'm submitting a ...**  (check one with "x")
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel at https://gitter.im/fossasia/open-event-orga-server

**Current behavior:**
<img width="1680" alt="screen shot 2017-06-07 at 7 50 18 pm" src="https://user-images.githubusercontent.com/2404372/26884305-17170fa8-4bbd-11e7-8b86-fbf9cb9f703e.png">

As you can see, no events are being displayed

**Expected behavior:**
_image deleted due to privacy issue_
These are the current live events. They should be displayed on the home page

**Steps to reproduce:**
- Goto the home page 

**Related code:**
The code related to querying the events based on time.

**Comment by SaptakS** [comment] 2017-06-07 18:43
@niranjan94 @magdalenesuo this isn't a bug. The system is working fine. It's only that the other events have a listing setting to privacy instead of public. So closing this issue.

**Closed** 2017-06-07 18:48 UTC
Labels: bug, Priority: High

**Comment by magdalenesuo** [comment] 2017-06-07 18:49
@SaptakS Thank you. I was eating my head off trying to find the cause.

**Comment by SaptakS** [comment] 2017-06-07 18:51
@magdalenesuo well you could never have found out. Because I guess you don't have admin access to check the privacy settings of events. So all cool. Thank you so much for your effort.
