### ISSUE TITLE
Leading "/" on endpoints are not working

### ISSUE THREAD

**Issue by championswimmer** [fossasia/open-event-orga-server#1595] opened 2016-07-12 18:55 UTC
For eg 
https://open-event-dev.herokuapp.com/api/v2/events/9/ 
does not work but 
https://open-event-dev.herokuapp.com/api/v2/events/9 
does.

To be safe, we should consider the request might have a leading "/" and handle it

**Comment by shivamMg** [comment] 2016-07-12 20:02
I'm putting this on hold. This is not a bug. It's how we've kept our spec. 

Here's a relevant discussion from another repo about the same: https://github.com/nicolaiarocci/eve/issues/118

Many top apis keep it this way. Twitter e.g. https://dev.twitter.com/rest/public (see the left panel). 

Adding this feature is simple. But it is failing all our tests, because the returned status code would be 301 (permanent redirect) for `/path/to` (which would redirect to `/path/to/`). I'll come back to it after implement permissions for APIs.

**Comment by shivamMg** [comment] 2016-07-21 21:24
I looked up at some other places where people had the same discussion. Here's a good one: https://groups.google.com/forum/#!topic/api-craft/L2YlSS7FmEk

It doesn't really seem to be a big issue for the client. Here's an important point though.

> Afaik, with & without trailing slash are two distinct URLs so you're potentially creating two cache entries for every resource by doing this.

> Why not just return a 404 and make this rule explicit in your API? Another thing, if your clients are following links this effectively becomes a non issue.

If clients follow the guide, this really isn't a big deal. I'm closing it for now.

**Closed by shivamMg** 2016-07-21 21:24 UTC

**Comment by snuggs** [comment] 2018-03-17 04:37
@shivamMg it's actually [405 is a better response](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405). But great call nonetheless.
