### ISSUE TITLE
Number of Sent Mails in Dashboard incorrect

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3080] opened 2017-01-30 10:30 UTC
The number of sent mails in the admin dashboard is not increasing even though a number of additional emails have been sent out, e.g. https://eventyay.com/admin/

![screenshot from 2017-01-30 11-28-47](https://cloud.githubusercontent.com/assets/1583873/22419808/66020ea8-e6df-11e6-9863-9a1e9fc5ab6b.png)

**Comment by Achint08** [comment] 2017-02-10 15:41
Can I work on this @mariobehling ?

**Comment by niranjan94** [comment] 2017-02-11 04:14
@Achint08 please proceed

**Comment by shubham-padia** [comment] 2017-04-09 21:10
Cannot reproduce the issue at the moment, every mail I could find uses the `send_email` function which logs and saves the mail to the db. Please reopen the issue if it still persists along with the mail info of the mail which was not added to the mail count. Closing this.

**Closed by shubham-padia** 2017-04-09 21:10 UTC
Labels: bug
