### ISSUE TITLE
Profile Icon does not show up on menu

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2430] opened 2016-09-18 07:54 UTC
Please see below. Expected behaviour: Icon should show up on top right.

![screenshot from 2016-09-18 09 53 35](https://cloud.githubusercontent.com/assets/1583873/18614003/eb598892-7d85-11e6-96e4-af58c619b1be.png)

**Comment by SaptakS** [comment] 2016-09-18 09:17
@mariobehling did you upload the image recently? Because like I said before, if you have it uploaded previously, then the method in which we are showing after resizing of images hasn't been applied because of which re-sized images aren't available. That is the reason for image not being shown in top right corner.

**Comment by SaptakS** [comment] 2016-09-18 09:18
@mariobehling however there is an error occurring while uploading using Amazon S3. It wasn't there previously. Will have to check.

**Comment by SaptakS** [comment] 2016-09-18 12:21
@mariobehling the issue has been fixed in #2432 . Please re-upload an image and confirm that the issue has been fixed. Thanks.

**Comment by mariobehling** [comment] 2016-09-18 13:18
I uploaded a new image and it shows as the icon, but now it is converted from a jpg to a png and much bigger than the original.

![screenshot from 2016-09-18 15 17 39](https://cloud.githubusercontent.com/assets/1583873/18615942/1382df58-7db3-11e6-90d0-40b50ac10a39.png)

**Comment by SaptakS** [comment] 2016-09-18 16:17
It is in jpg for me.

![image](https://cloud.githubusercontent.com/assets/9530293/18617265/6a69a23a-7de9-11e6-9a20-b38a5ee81a24.png)

Can you please check?

**Comment by mariobehling** [comment] 2016-09-19 09:11
See here: https://opevbucketname.s3.amazonaws.com/users/4/avatar/UmdLcjVEYm/1474204504.49.png

Over the admin panel you can also view all user accounts: http://open-event-dev.herokuapp.com/admin/users/

My profile http://open-event-dev.herokuapp.com/admin/users/4/

**Comment by SaptakS** [comment] 2016-09-19 10:12
@mariobehling yeah it's getting converted to png that I agree because of the cropping property, but it is not being used. The images used are the resized jpg images. 

I missed out the admin panel. Will fix that.

**Comment by sainiak009** [comment] 2016-10-04 03:53
I still can't see profile icon anywhere on navigation bar. Can you explain me current condition of this issue ?

**Comment by SaptakS** [comment] 2016-10-05 01:34
@sainiak009 did you upload your profile pic? Can you share a screenshot with us to understand your situation better?

**Comment by sainiak009** [comment] 2016-10-05 03:53
@SaptakS I still can't see profile icon anywhere on navigation bar :

![screenshot 35](https://cloud.githubusercontent.com/assets/13566432/19100530/3fafaaa2-8add-11e6-9748-9983fc6aac04.png)

**Comment by nikhilrayaprolu** [comment] 2016-10-05 21:21
@SaptakS @sainiak009 It has  worked well for me , the problem is only when we login using facebook or google for me

**Closed** 2016-10-19 01:47 UTC
Labels: bug, hacktoberfest
