### ISSUE TITLE
Cannot drag a session to the schedule if calendar is off-screen

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3227] opened 2017-02-21 02:27 UTC
If a session is listed off-screen, the user cannot drag it to the calendar.

![screenshot from 2017-02-21 10-24-53](https://cloud.githubusercontent.com/assets/1583873/23148371/42a13fcc-f820-11e6-97ab-341e135b653d.png)

**Comment by poush** [comment] 2017-02-21 19:54
I think it should be solved by #3219 as this issue looks like duplicate of #3217

**Closed** 2017-02-22 14:03 UTC
Labels: bug, Priority: High, Priority: URGENT, Scheduling
