### ISSUE TITLE
Location interface not working properly 

### ISSUE THREAD

**Issue by Amritanshu54** [fossasia/open-event-orga-server#2861] opened 2017-01-07 18:22 UTC
I had the the GCI 2016 Task -> Open Event Orga Server: Add and test events in eventyay (FOSSASIA)

I had a problem entering the venue of the event. As I would enter the venue, either it won't accept it or the map won't show it. Also when I try adding the name of the country ( or say anything) first , it doesn't appear there. So I request you to look into this issue

**Comment by niranjan94** [comment] 2017-01-07 20:21
Duplicate of #2810

**Closed by niranjan94** 2017-01-07 20:21 UTC
