### ISSUE TITLE
Add good quality images to be used as placeholders for events without an event image

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#1845] opened 2016-07-24 17:33 UTC
Currently if an event does not have an image, we show a gray placeholder image as below.

![screenshot from 2016-07-24 19 25 17](https://cloud.githubusercontent.com/assets/1583873/17085271/8cb9f6b4-51d4-11e6-8e90-9be4585a25ff.png)

For events that do not have images, we should find a better more colorful solution. A way to implement it, is to use the categories and subcategories, that are entered in the wizard step 1.
![screenshot from 2016-07-24 19 28 48](https://cloud.githubusercontent.com/assets/1583873/17085293/e5fb9bb0-51d4-11e6-8651-52bf300cafa9.png)

Please improve the visuals of the system by adding good quality images:
- [x] Find good quality images, that do not require a license mentioning, e.g. from https://pixabay.com or elsewhere for each combination of event type, event topic, and subtopic.
- [x] Ensure that images are as neutral as possible (basically they need to be somewhat relevant and generic)
- [x] Implement that events use the image in the overview and event page, if the organizers did not specify their own image.

**Comment by mariobehling** [comment] 2016-08-02 07:07
Please check if you find some better images and compare on Google image search what kind of images are most relevant.

* [ ] Please add copyright/copyleft/origin info of each info into comments
* [ ] What is the best size and resolution of images? At the moment the images have different sizes from 100-200+KB
* [ ] We need higher quality images and images should not have a too close relation to a specific field, e.g. the picture spirituality currently is related to Buddhism
* [ ] As we will have an international site, images should not have text on it, e.g. "Charity"

Some hints
  * [ ] The photo of the car engine looks stretched
  * [ ] Business photo is not professional enough
  * [ ] Charity photo has text
  * [ ] Culture: Photo quality not sufficient
  * [ ] Food: Better quality needed
  * [ ] Generic: no English text please
  * [ ] Hobbies: Something more generic
  * [ ] Holiday: Better quality image and more relevant image needed
  * [ ] Spiritual: Image needed that is religion independent
  * [ ] Home: More relevant picture and higher quality

E.g. compare these search results for home and our "home" picture:
![screenshot from 2016-08-02 09 05 58](https://cloud.githubusercontent.com/assets/1583873/17319774/6e87d068-5890-11e6-8b3f-80cecf41e3af.png)

**Comment by SaptakS** [comment] 2016-08-02 17:36
@mariobehling I did try finding images keeping all the above points in mind. Google doesn't show open licensed photos. And the photos I got from free and open licensed website were these.. I will try to find better.. I know some of them are not generic enough.. I also couldn't find any generic image for government and politics. The problem is we can only use open licensed images.

**Comment by mariobehling** [comment] 2016-08-02 18:01
Please document, where you found the photos. Which services? And ask others for input.

**Comment by mariobehling** [comment] 2016-08-02 18:03
First page of pixabay already shows suitable photos in great quality: https://pixabay.com

**Comment by mariobehling** [comment] 2016-08-02 18:05
Please also add a dedicated photo for each subcategory. If subcategory is not chosen, use the photo of the main category.

**Comment by SaptakS** [comment] 2016-08-02 18:43
I searched in https://pixabay.com itself. And I will do for the subcategory as well..

**Comment by mariobehling** [comment] 2016-08-02 18:45
@SaptakS Ok, maybe this is tricky and a better implementation would be to give the administrator the option to change the topic/subtopic image. So, please implement a standard image and give the admin the option to change it in a subtab of `admin/content/` as defined in https://github.com/fossasia/open-event-orga-server/issues/2016

**Comment by SaptakS** [comment] 2016-08-03 02:18
@mariobehling I was thinking about this as well. But suppose the administrator uses some premium images. It won't create issues for us, right?

**Comment by mariobehling** [comment] 2016-08-03 07:15
No issue for us, as the admin will be responsible and we just care about our source code. Issue #2016 also outlines to create a form field for additional info about the image. The admin can add origina info and a link there, but we do not display that online. That is just for the internal info.

**Comment by mariobehling** [comment] 2016-08-03 17:08
Images are implement on top of placeholder images slowing down the website. Please correct that everywhere.

![screenshot from 2016-08-03 19 05 58](https://cloud.githubusercontent.com/assets/1583873/17374588/987a8a96-59ad-11e6-85d5-0ac3148524c6.png)

**Comment by SaptakS** [comment] 2016-08-24 22:32
@mariobehling now the admin himself can set images for the placeholder as in #2016 . What are the things we need to do now in this issue? The only thing I recon is we need to add pictures for subcategories as well which I am doing. Anything else? Should I search for some better default placeholders as well or leave it to the admin to upload his own?

**Comment by mariobehling** [comment] 2016-08-26 17:29
Yes, thank you. Only find a few more images for the subcategories. No need to find more suitable images. We can ask others to do this. It is simple.

**Comment by SaptakS** [comment] 2016-08-26 18:36
Yes. @mariobehling we can even keep this as a GCI task I guess.

**Comment by mariobehling** [comment] 2016-08-26 20:14
Thank you. So, please implement the structure and add some images. They can be changed later.

**Comment by SaptakS** [comment] 2016-08-26 20:15
Yes. Working on it.

**Comment by SaptakS** [comment] 2016-11-16 17:32
@mariobehling this is supposed to be a GCI task. The structure is already implemented. And we discussed that more images for the sub categories can be added by GCI participants. So I think we shouldn't be adding beta-release. What do you think?

**Comment by mariobehling** [comment] 2016-11-17 04:57
Yes, correct.
Could you make a list of the images needed, please?
Which size is the standard size?

**Comment by SaptakS** [comment] 2016-11-17 05:11
I will do that. What I wanted to know is is this feature necessary for release?? Because since this is a gci task, I am guessing I wont be completed before December. And we are targeting release in November. So I thought maybe beta-release label is not appropriate.

**Comment by PolBaladas** [comment] 2016-11-28 18:03
Hi there!
I've got a little nice image scraping script (scrapes pixabay). Would it be interesting to automatically get the pics that are needed? @mariobehling

**Comment by PolBaladas** [comment] 2016-11-28 18:28
That'd be much faster

**Comment by SaptakS** [comment] 2016-11-28 22:22
@PolBaladas we actually don't need all images but a single image for each subcategory which is just the default image. It is later completely customisable and the one hosting the server or anyone with admin level access can change it later. So I don't think you need scraping as such.You need to checkout the sub-categories and find images accordingly.

**Comment by PolBaladas** [comment] 2016-11-28 22:34
Yeah, okay. I meant that if someone used the script it would be a faster method to get the pics, for exampe using a list with subcategories and taking the first pic each time. 

Anyway, I get it now, Thanks! @SaptakS.

**Comment by SaptakS** [comment] 2016-11-28 22:38
Well first pic might not always be the best one. Otherwise I do agree with your approach

**Comment by PolBaladas** [comment] 2016-11-28 22:39
Okay then. We could maybe pick first 5 pics and select from there? I don't know if this would be impractical or not. Thanks

**Comment by PolBaladas** [comment] 2016-11-28 22:40
How many categories are there?

**Comment by PolBaladas** [comment] 2016-11-30 00:52
What do you think @mariobehling ?

**Comment by mariobehling** [comment] 2016-11-30 01:07
Please let's keep it simple. Discussion on this issue is already very long.

**Comment by PolBaladas** [comment] 2016-11-30 06:54
Okay.

**Comment by PolBaladas** [comment] 2016-12-05 12:13
Do we have a list of images that need to be uploaded? @SaptakS

**Comment by niranjan94** [comment] 2016-12-05 12:19
@PolBaladas yes. You can see the topics and subtopics at [app/helpers/static.py](https://github.com/fossasia/open-event-orga-server/blob/development/app/helpers/static.py)

**Comment by PolBaladas** [comment] 2016-12-05 13:06
Great! Thanks @niranjan94

**Comment by PolBaladas** [comment] 2016-12-05 13:18
What about 133KB (or 272KB) for images and 25KB for thumbnails? @niranjan94 @mariobehling

**Comment by SaptakS** [comment] 2016-12-05 13:52
> 25KB for thumbnails

@PolBaladas you don't need to save separately the thumbnails. When you upload the image, it automatically gets saved in 3 size formats - thumbnail, logo and icon

> What about 133KB (or 272KB) for images

I think it is cool. But still check once to see whether the resolution is poor. If so you can try something with better resolution

**Comment by PolBaladas** [comment] 2016-12-05 13:55
But this is for placeholder images, right? The ones we define not the ones the user will upload. So we need to include thumbnails.

**Comment by PolBaladas** [comment] 2016-12-05 15:42
Sorry, couldn't resist to scrape it. I've got a script downloading all required images (reads from [/app/helpers/static.py)](open-event-orga-server/app/helpers/static.py)

**Comment by Abhi2424shek** [comment] 2017-01-08 10:28
This issue is looming large, can I go for a complete fix pls.

**Comment by SaptakS** [comment] 2017-01-08 10:35
> can I go for a complete fix pls.

What do you have in mind?

**Comment by niranjan94** [comment] 2017-01-10 16:51
I think we already have a set of good pictures given by @PolBaladas in #2648. That covers the scope of this ticket. Anything more could be dealt with in a new ticket. So closing this for now.

@Abhi2424shek if you wish to contribute alternative images please do go ahead with a PR referencing this issue (even if it is closed). Would love to have more contributions :smile:

**Closed by niranjan94** 2017-01-10 16:51 UTC
Labels: enhancement, GCI Task, Images, UI
