### ISSUE TITLE
Creating an event with logo does not work.

### ISSUE THREAD

**Issue by suheb** [fossasia/open-event-orga-server#178] opened 2016-01-23 16:37 UTC
Steps to reproduce:
1. Click on "Create New Event" on home page.
2. Fill in the required fields.
3. Choose any file for the logo field. This step is important.
4. Click on "Submit".
This gives an internal server error.
Tested on both local machine and <a href="http://open-event.herokuapp.com/admin/">Demo site</a>.
It should be noted that this does not happen when logo field is left empty.

**Comment by leto** [comment] 2016-01-24 02:22
Verified that this happens. Part of the problem is that `static/event_logo` needs to exist, which it doesn't. Even then, `create_event` in `open_event/helpers/data.py` doesn't work correctly any more.

**Comment by creativepsyco** [comment] 2016-02-16 05:06
I believe everywhere now we are using urls for images and files. We cannot guarantee file storage successfully because of issue #184 please check this issue again and close this if it is working as prescribed.

**Comment by suheb** [comment] 2016-02-16 09:49
Closing as this is effectively fixed by [this](https://github.com/fossasia/open-event-orga-server/commit/45771fd5f294545e72c777feffb1cece0a110132)

**Closed** 2016-02-16 10:26 UTC
