### ISSUE TITLE
Add png export to public schedule page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3295] opened 2017-03-04 06:46 UTC
We already have a png export of the schedule, but it is only implemented for the organizers. It also has issues as it only exports the screen view and not always the full calendar.

Please implement the following:
* [ ] Add png export to the public schedule page e.g. https://eventyay.com/e/45da88b7/schedule/
* [ ] Ensure that the whole schedule is exported including areas that might be off-screen

![screenshot from 2017-03-04 14-43-40](https://cloud.githubusercontent.com/assets/1583873/23576750/2f74ebb6-00e9-11e7-8137-c1db6919a12b.png)

**Comment by poush** [comment] 2017-03-05 17:23
I tried creating a solution. Here is the sample export I'm able to download 
![timeline 88](https://cloud.githubusercontent.com/assets/1812082/23589628/7804771c-01f6-11e7-9b7e-cf8850131c67.png)

**Comment by poush** [comment] 2017-03-05 17:28
The concept is that I give the timeline full width for a moment to generate export 

![screenflow](https://cloud.githubusercontent.com/assets/1812082/23589660/262eb276-01f7-11e7-98a2-48b5c6ba746f.gif)

**Comment by poush** [comment] 2017-03-05 17:30
We can fade the screen with some popup or modal saying your export is in the process for this moment of the export process. 
@mariobehling @niranjan94 @SaptakS Would like to know your suggestions on this.

**Comment by mariobehling** [comment] 2017-03-06 01:20
@poush Thanks, please make a PR and iterate from there to see if the fade solution is more elegant.

**Comment by mariobehling** [comment] 2017-03-08 09:12
@poush Thanks for implementing this. In order to be fully functional the complete width of all tracks needs to be exported. The currently implemented version only exports the visible area. Please see below.

![timeline](https://cloud.githubusercontent.com/assets/1583873/23697338/604d5a16-0422-11e7-9038-486a5bcd211b.png)

**Comment by mariobehling** [comment] 2017-03-08 09:15
The "Export PNG" button should be located behind the "Sessions View" button (on the right of it).

Testing the full schedule view also only some areas of the schedule are exported as png.

**Comment by poush** [comment] 2017-03-09 03:50
@mariobehling Can you tell me how many rooms were there in that schedule?

**Comment by poush** [comment] 2017-03-09 03:57
If this was the schedule,

![timeline](https://cloud.githubusercontent.com/assets/1812082/23735277/981e080e-04aa-11e7-8a8f-7d45e5a7a524.png)

**Comment by mariobehling** [comment] 2017-03-09 06:10
@poush It is working now. Awesome!

I still see open issues on your screenshot though still:
a) Background is partly transparent. It should be white
b) The last column is not desired. It does not have a track (after Tinkering studio).
c) The expansion icon jumps to the dates
d) The "Export PNG" button should be behind/after "Session View" - Actually can we change this button to a download symbol as well?

It this is too much in this issue, please open new issues.

**Comment by poush** [comment] 2017-03-12 06:39
- [ ] Background is partly transparent. It should be white
- [ ] The last column is not desired. It does not have a track (after Tinkering studio).
- [ ] The expansion icon jumps to the dates
- [ ] The "Export PNG" button should be behind/after "Session View" - Actually can we change this button to a download symbol as well?

**Comment by mariobehling** [comment] 2017-03-12 10:13
> The expansion icon jumps to the dates

Seems to be solved as well.

There is now a tiny symbol "f()65" on the top of exported pngs. Any idea?

![screenshot from 2017-03-12 18-11-52](https://cloud.githubusercontent.com/assets/1583873/23830871/7a6708b8-074f-11e7-83d0-20c9654a9b58.png)

**Comment by poush** [comment] 2017-03-12 13:18
@mariobehling can't reproduce it. Even at the eventyay.com there is no such symbol 
<img width="1440" alt="screen shot 2017-03-12 at 6 46 54 pm" src="https://cloud.githubusercontent.com/assets/1812082/23832099/60b023f0-0754-11e7-81b6-8e9a8d10fb6a.png">

**Comment by poush** [comment] 2017-03-12 13:21
@mariobehling another issue has been created for background part. If other things are working fine then please close the issue.

**Closed** 2017-03-12 13:40 UTC
Labels: enhancement, Priority: High, Priority: URGENT
