### ISSUE TITLE
Adding user image to profile and saving it results in error page

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#2794] opened 2016-12-31 14:37 UTC
After user uploads an image to the profile page and updates/saves the profile an error page shows up.

![screenshot from 2016-12-31 15-36-41](https://cloud.githubusercontent.com/assets/1583873/21577975/160aba80-cf6f-11e6-999a-d42a21e9561b.png)

**Comment by nikhilrayaprolu** [comment] 2017-01-04 17:24
@mariobehling @SaptakS I amn't facing any issue on my computer , but this problem persists on http://open-event-dev.herokuapp.com and eventyay

**Comment by mariobehling** [comment] 2017-01-11 20:38
@SaptakS Any updates?

**Comment by SaptakS** [comment] 2017-01-11 21:01
This issue doesn't come up in local system. However occurs in deployments. I did check in heroku which gave a R14 memory error. Will check for kubernetes. Problem is since I cant recreate in local system its a little difficult. I will try to solve this issue by tomorrow.

**Comment by SaptakS** [comment] 2017-01-12 23:07
@mariobehling figured out the issue why it works properly in local system but not in deployments. The problem is in local system, the absolute path of the image returned is correct however in deployment we use AWS which now due to some reason returns a wrong path. I will get this fixed by today. :)

**Comment by mariobehling** [comment] 2017-01-12 23:20
@SaptakS We are using AWS in Heroku I think, but for eventyay/master branch we are using Google Cloud.

**Closed** 2017-01-13 04:45 UTC
Labels: bug, design

**Comment by SaptakS** [comment] 2017-01-13 05:31
@mariobehling the reason was same. The temporary image that we use to give a preview should be saved where the files are saved i.e. in heroku or kubernetes. After that when we press "Upload Changes" button, it resizes from the local image copy and uploads it to either AWS or Google Cloud. The error was it was uploading directly to AWS or Google Cloud and then it was unable to create a proper path to read the temporary image and resize.

So, I am sure since it works in heroku, it should also work in eventyay, once the development branch is merged in master.
