### ISSUE TITLE
Notifications for one and the same activity appear twice

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3111] opened 2017-02-01 10:32 UTC
A similar bug happened on the emails before. The notifications show up twice for the same activity.

![screenshot from 2017-02-01 11-31-00](https://cloud.githubusercontent.com/assets/1583873/22503438/0d3a9aee-e872-11e6-828d-bb99d9c1716c.png)

**Comment by poush** [comment] 2017-02-10 07:14
@mariobehling Can't reproduce here (tried booking ticket for one event in local machine). Can you suggest some steps for same ?

**Comment by mariobehling** [comment] 2017-03-05 11:29
@poush Maybe try as an admin.

I am now receiving notifications 3 times.

![screenshot from 2017-03-05 19-28-48](https://cloud.githubusercontent.com/assets/1583873/23586893/0f4cdd34-01da-11e7-88c0-5b75a575ba2f.png)

**Comment by guptasimran66** [comment] 2017-03-20 10:44
@mariobehling would like to work on this

**Comment by niranjan94** [comment] 2017-03-20 12:09
@guptasimran66 set up the app locally and add a comment here once you're done and we'll assign this issue to you.

**Comment by guptasimran66** [comment] 2017-03-21 08:41
@niranjan94 Done with the set up and can run on localhost.

**Comment by niranjan94** [comment] 2017-03-21 10:04
@guptasimran66 please proceed :)

**Comment by magdalenesuo** [comment] 2017-05-25 05:49
I think this PR #3634 would have already fixed this issue.
Closing it.

**Closed by magdalenesuo** 2017-05-25 05:49 UTC
Labels: bug, notifications
