### ISSUE TITLE
Application error on attempt to export Pentabarf XML data

### ISSUE THREAD

**Issue by heysadboy** [fossasia/open-event-orga-server#3586] opened 2017-05-14 09:38 UTC
I tried to export the FOSSASIA 2016 data in pentabarf xml format but this gives application error. Also the link to go to .xml file is not working even when the event is live

![screenshot 120](https://cloud.githubusercontent.com/assets/22588035/26032703/267b38fc-38b7-11e7-9f0f-5cd5e2e06f8b.png)

![screenshot 114](https://cloud.githubusercontent.com/assets/22588035/26032697/0ab77306-38b7-11e7-8b2c-756427c2bd60.png)

**Comment by niranjan94** [comment] 2017-05-14 09:40
Looks like it's failing because the event is too big and the connection times out before the the XML is generated ...

A possible fix would be,
To generate the XML in the background via Celery and store the file in the preferred storage (every time any session/event data is edited) and serve the file when required.

**Comment by heysadboy** [comment] 2017-05-14 09:42
@niranjan94 Sure, I could help with this. I need this to add support to Giggity.

**Comment by SaptakS** [comment] 2017-05-17 14:42
@niranjan94 @heysadboy isn't this issue related to (or maybe same) [this](https://github.com/fossasia/open-event-orga-server/issues/3299) ?

**Comment by SaptakS** [comment] 2017-05-17 14:43
Closing as the duplicate of https://github.com/fossasia/open-event-orga-server/issues/3299

**Comment by heysadboy** [comment] 2017-05-17 14:43
@saptaks Yes.

**Closed by SaptakS** 2017-05-17 14:43 UTC
