### ISSUE TITLE
Zip Download show "Not Found" after generating zip

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3228] opened 2017-02-22 04:11 UTC
After the user generates a zip and clicks on "Download" a message is shown "Not Found". Apparently the image is generated, but it seems the link is wrong.

![screenshot from 2017-02-22 12-08-32](https://cloud.githubusercontent.com/assets/1583873/23196976/f5ed85c2-f8f7-11e6-9c37-d07a0ad2e293.png)

**Comment by CosmicCoder96** [comment] 2017-02-23 06:13
@mariobehling I would like to work on this one.

**Comment by CosmicCoder96** [comment] 2017-02-25 08:29
@mariobehling   I was trying to reproduce it, but each time the event exported successfully with and without images. Can you point out an specific instance where it  occurred? I tested with multiple events on localhost as well as heroku deployment.

**Comment by mariobehling** [comment] 2017-02-25 13:54
@CosmicCoder96 Does not work on current FOSSASIA Summit 2017.

@niranjan94 Could that be connected to the Google Cloud deployment?

![screenshot from 2017-02-25 21-47-46](https://cloud.githubusercontent.com/assets/1583873/23331639/f71dcf60-fba4-11e6-82ee-6ac3a0ef6566.png)

![screenshot from 2017-02-25 21-53-33](https://cloud.githubusercontent.com/assets/1583873/23331637/f4294230-fba4-11e6-8d32-05aa199e5a58.png)

**Comment by niranjan94** [comment] 2017-02-25 14:48
@mariobehling yes. This is connected to the deployment. The code has to use the correct shared NFS server to store the file. It's supposed to be used automatically ... (Import functionality uses it correctly .. Looks like export is not ...)

**Comment by niranjan94** [comment] 2017-02-25 14:54
@mariobehling @CosmicCoder96 

In kubernetes deployment, we have celery and web server running on separate pods (containers). Export is done in celery. So, when celery generates the zip, it stores the zip in it's pod. Not in the web server's pod. So, to share files between both pods, we have a shared folder located at `config['BASE_DIR'] + '/static/uploads/'` ... Any files in this folder will be accessible by both pods. 

@CosmicCoder96 to resolve this, the export code has to be modified such that it generate the zip and stores it in this folder. Then it'll be accessible by the web pod. (Hence download will also work)

**Comment by niranjan94** [comment] 2017-02-25 14:58
I know the shared folder says _uploads_ ... Since it was first used for import functionality. But let's just use the same folder now irrespective of what it's called ... Because changing the folder will need some careful modification in kubernetes config and every place where it is used ... So, let's not risk affecting other parts of the application and just use the same folder for now.

**Comment by CosmicCoder96** [comment] 2017-03-05 08:58
@niranjan94 
Please assign this to someone else. I will be away for a few days.

**Comment by SaptakS** [comment] 2017-03-07 07:56
@mariobehling this issue has been fixed.

**Closed by SaptakS** 2017-03-07 07:56 UTC
Labels: bug, Import-export, Priority: High
