### ISSUE TITLE
Speakers Proposal Acceptance: Add Status "Confirmed"

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3085] opened 2017-01-30 13:27 UTC
After a speaker submits a proposal currently there are the following states: 1. Pending, 2. Accepted, 3. Rejected.

When the session is accepted the speaker receives the info that he is accepted. The organizer still does not have any info if the speaker is really confirmed and has booked the travel. Therefore we need an additional state "Confirmed"

Please implement an additional button "Confirmed" and a filter on the status filter of the page.

![screenshot from 2017-01-30 14-23-38](https://cloud.githubusercontent.com/assets/1583873/22424738/2a5a79bc-e6f8-11e6-9472-51e89c30993b.png)

**Comment by nishapoyarekar** [comment] 2017-02-19 04:45
I would like to work on this. @SaptakS can you please assign this issue to me?

**Comment by niranjan94** [comment] 2017-02-19 06:41
@nishapoyarekar you can proceed

**Comment by nishapoyarekar** [comment] 2017-02-27 08:49
My understanding of the issue is that once Accepted, a mail needs to be sent to the speaker asking them to confirm their availability for the session.
I have attached a screenshot with the change-
<img width="1265" alt="confirmationemailiconandfilter" src="https://cloud.githubusercontent.com/assets/20510268/23354551/b81fc940-fcf7-11e6-98bd-a56408fbbd7d.png">
<img width="1087" alt="confirmationemail" src="https://cloud.githubusercontent.com/assets/20510268/23354550/b81fa1c2-fcf7-11e6-9ab2-00176f7cd983.png">


Is this what is expected?

**Comment by mariobehling** [comment] 2017-02-27 08:59
Yes, the right direction. Please implement as follows:
* [ ] Change color of green accepted buttons to yellow
* [ ] After session is accepted fffer two buttons in green with
   * [ ] a) Confirm without email
   * [ ] b) Confirm with email
* [ ] Keep the red buttons to reset the status to "rejected" if organization of sessions requires this at a later stage.

**Comment by mariobehling** [comment] 2017-03-07 01:40
@nishapoyarekar Thanks for the commit. Please change the color in accepted to "yellow" (not orange).

Currently it is not possible to send an email to "sessions pending".

![screenshot from 2017-03-07 09-38-24](https://cloud.githubusercontent.com/assets/1583873/23638022/19743f6e-031a-11e7-8888-f60a0e79f5bf.png)

**Comment by Himanshi-Khandelwal** [comment] 2017-03-25 06:40
@nishapoyarekar are you working on this?

**Comment by Himanshi-Khandelwal** [comment] 2017-03-25 08:51
If no one then I'll like to do the change.

**Comment by nishapoyarekar** [comment] 2017-03-25 08:55
@Himanshi-Khandelwal I wont be working on this right now. Thanks for checking with me :)

**Comment by Himanshi-Khandelwal** [comment] 2017-03-25 09:38
@mariobehling  @niranjan94  is this ok ?
![screenshot from 2017-03-25 15 07 32](https://cloud.githubusercontent.com/assets/17119462/24321203/ee48e5ea-116c-11e7-9b99-dbb4364184c7.png)

**Comment by Himanshi-Khandelwal** [comment] 2017-03-29 18:07
@niranjan94 if this is OK , then I will proceed to make the PR.

**Closed** 2017-05-15 15:59 UTC
Labels: enhancement, feature
