### ISSUE TITLE
Schedule Page: Left menu sidebar disappearing and jumping on scrolling in Chrome

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3592] opened 2017-05-15 09:48 UTC
Left menu sidebar is acting strangely and disappearing at times when the user scrolls.

Compare: https://eventyay.com/e/5642d9a1/schedule/
![screenshot from 2017-05-15 11-46-29](https://cloud.githubusercontent.com/assets/1583873/26051983/534d3ff8-3964-11e7-9f0e-549f50ada68e.png)

**Comment by SaptakS** [comment] 2017-05-15 09:50
Duplicate of https://github.com/fossasia/open-event-orga-server/issues/3546. Closing.

**Closed by SaptakS** 2017-05-15 09:50 UTC
Labels: bug, duplicate
