### ISSUE TITLE
Social Login: Signup without password

### ISSUE THREAD

**Issue by roschaefer** [fossasia/open-event-orga-server#3564] opened 2017-05-03 11:48 UTC
I thought the whole point of social logins was a login without username or password. When I create an account prior to the procedure in #3565 and I click on "Login with Google" I still have to provide a password. Why?

**Comment by mariobehling** [comment] 2017-05-03 13:03
We are still not sure, where we are heading with social logins and trying to figure out the policies, e.g. Facebook sometimes only allows to save data for a certain time. This would be bad, if a speaker registers and then we have to delete parts of the data because FB requires that. Therefore we implemented this in a way just as other service do it, e.g. sign up with a social media account on pinterest and you will see that the process is even more complicated. We will figure out if we will change this and how to make this process smoother. For the above reasons and to ensure the service is - for now - also working without FB and Google we are keeping the requirement for a password.

Still there are other bugs that are unrelated to this issue and we acknowledge these need to be solved. Thanks for helping! As this is not a bug, but currently an intended process I am closing this issue. Cheers.

**Closed by mariobehling** 2017-05-03 13:03 UTC
