### ISSUE TITLE
Giving password with length less then 4

### ISSUE THREAD

**Issue by jack17529** [fossasia/open-event-orga-server#3438] opened 2017-03-29 10:29 UTC
Giving password of less then 4 characters gives an unusual error ,instead of asking for rewriting good strong password.

Here is the log file - 

vagrant@vagrant-ubuntu-trusty-64:confused:vagrant$ python create_db.pyINFO [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO [alembic.runtime.migration] Will assume transactional DDL.
Your login is 'super_admin'.
Enter email for super_admin : jack17529@gmail.com
Enter password for super_admin :

Password should have minimum 4 characters
Exception in thread APScheduler (most likely raised during interpreter shutdown):
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 810, in bootstrap_inner
File "/usr/lib/python2.7/threading.py", line 763, in run
File "/usr/local/lib/python2.7/dist-packages/apscheduler/schedulers/blocking.py", line 28, in _main_loop
File "/usr/lib/python2.7/threading.py", line 620, in wait
File "/usr/lib/python2.7/threading.py", line 358, in wait
File "/usr/local/lib/python2.7/dist-packages/eventlet/greenthread.py", line 36, in sleep
File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/timer.py", line 71, in cancel
File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/init__.py", line 116, in get_hub

<type 'exceptions.TypeError'>: 'NoneType' object is not callable

**Comment by jack17529** [comment] 2017-03-29 10:30
Please assign me this issue.

**Comment by niranjan94** [comment] 2017-03-29 13:59
<img width="1680" alt="screen shot 2017-03-29 at 7 28 12 pm" src="https://cloud.githubusercontent.com/assets/2404372/24458202/de450894-14b5-11e7-9f57-26f09c2ea0b8.png">

As you can see above, this works fine. Looks like the issue is on your side. See if you have installed all the necessary packages. Especially, check if eventlet server is installed.

Closing this issue until then.

**Closed by niranjan94** 2017-03-29 13:59 UTC
