### ISSUE TITLE
Adding Registrars and Moderators leads to Error Pages like Access Denied

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3656] opened 2017-05-24 13:01 UTC
1. Adding Registrars is not possible. User cannot accept the link and received error page.
Expected: Registrar can view tickets and add ticket holders via web checkin.

2. Moderator: Can accept the link, but immediately receive "Access Denied".
![screenshot from 2017-05-24 14-58-24](https://cloud.githubusercontent.com/assets/1583873/26404297/ac1896ee-4091-11e7-9dd0-2892c3236c0c.png)

Expected: Moderator can view sessions and speakers.

**Comment by poush** [comment] 2017-05-25 14:47
I would like to work on this.

**Comment by poush** [comment] 2017-05-26 10:04
It seems the issue is related with permission to access the events home page. I have added a fix for registrar so that they will be able to see (redirect to) attendee section. I would like to know about the moderator permission, are they allowed to view the event home page?

**Comment by poush** [comment] 2017-05-26 16:13
@SaptakS @niranjan94 Can you please assign this to me.

**Closed** 2017-05-27 08:19 UTC
Labels: bug
