### ISSUE TITLE
G+ login broken

### ISSUE THREAD

**Issue by tabesin** [fossasia/open-event-orga-server#2418] opened 2016-08-31 12:57 UTC
Logging in via Google+ at the dev installation (https://open-event-dev.herokuapp.com) results in "did not find user info" msg.

**Comment by nikhilrayaprolu** [comment] 2016-09-21 10:13
@mariobehling @niranjan94 I tried to reproduce the error on the dev installation (https://open-event-dev.herokuapp.com) and the login was successful . I am not able to reproduce the error. 
can some one show me the procedure followed when the error was reproduced. 
if the problem is only on localmachine some resources online show that the error is due to 
1) may be google plus api was not activated in your developer console
2) may be you are accessing it on localhost trying to access it  on 127.0.0.1 may work perfect

**Comment by mariobehling** [comment] 2016-09-21 10:27
ok, good. closing it then.

**Closed by mariobehling** 2016-09-21 10:27 UTC
Labels: bug
