### ISSUE TITLE
Dates on tracks page do not link to the specified date (there is no date section)

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-orga-server#3256] opened 2017-02-25 17:25 UTC
The dates shown do not have a function or link to a date section. There are not any date sections actually.

![screenshot from 2017-02-26 01-24-14](https://cloud.githubusercontent.com/assets/1583873/23333197/5cda2098-fbc2-11e6-896e-2cad1f364502.png)

**Comment by Himanshi-Khandelwal** [comment] 2017-03-19 13:49
@mariobehling so, where to redirect the user if the user click on date?

**Comment by niranjan94** [comment] 2017-03-19 13:57
@Himanshi-Khandelwal No redirect. When a date is clicked, the sessions shown below should be filtered to show only those that are on that date.

**Comment by Himanshi-Khandelwal** [comment] 2017-03-20 02:58
@niranjan94 this is already happening. When I clicked on dates , session of that date are showing.
![screenshot from 2017-03-20 08 25 42](https://cloud.githubusercontent.com/assets/17119462/24087601/f7856680-0d46-11e7-84e4-0055730694f5.png)
![screenshot from 2017-03-20 08 25 59](https://cloud.githubusercontent.com/assets/17119462/24087603/f7881718-0d46-11e7-9c42-3481bd2ff539.png)
![screenshot from 2017-03-20 08 26 14](https://cloud.githubusercontent.com/assets/17119462/24087602/f787961c-0d46-11e7-82d0-68b1931b3c3a.png)

**Comment by niranjan94** [comment] 2017-03-20 04:23
@Himanshi-Khandelwal please look at the attached screenshot in the Issue description. The problem is in the tracks view. You're looking at the rooms view.

**Comment by Himanshi-Khandelwal** [comment] 2017-03-20 10:18
@niranjan94 this is happening
![screenshot from 2017-03-20 15 44 23](https://cloud.githubusercontent.com/assets/17119462/24095709/563d22e8-0d84-11e7-8e97-0489ab37939f.png)
![screenshot from 2017-03-20 15 45 31](https://cloud.githubusercontent.com/assets/17119462/24095711/56af7686-0d84-11e7-900f-a9762506c320.png)

**Comment by Himanshi-Khandelwal** [comment] 2017-04-06 01:51
What I found is that when a date is clicked, the sessions shown below are filtered to show only those that are on that date. What needs to be done here then?

**Comment by SaptakS** [comment] 2017-04-11 20:28
@mariobehling @niranjan94 this issue must have been resolved by some other PR. It works fine now. Closing.

**Closed by SaptakS** 2017-04-11 20:28 UTC
Labels: bug
